site_name: O11y Event Emitter
site_url: https://tjohander-splunk.github.io/o11y-custom-event-emitter
theme:
  name: material
  font:
    text: "Century Gothic"
    code: Roboto Mono
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.ico
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Overview: 'overview.md'
  - Pre-Requisites: 'pre-reqs.md'
  - Provisioning AWS Resources:
      - Provision AWS Resources via Automation (Recommended): 'provisioning-automated.md'
      - Provision AWS Resources (Not Recommended): 'provisioning-manual.md'
  - Execute the Demo: 'execute-demo.md'