AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  o11y-event-emitter-lambda

  Sample SAM Template for o11y-event-emitter-lambda

Parameters:
  Realm:
    Type: String
  AccessToken:
    Type: String
    NoEcho: true
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ACCESS_TOKEN:
          Ref: AccessToken
        REALM:
          Ref: Realm


Resources:
  O11yEventEmitterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: o11y-event-emitter/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-2:455790677231:codestar-notifications-spring-pet-clinic

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  O11yEventEmitter:
    Description: "O11y Event Emitter Lambda Function ARN"
    Value: !GetAtt O11yEventEmitterFunction.Arn
  O11yEventEmitterIamRole:
    Description: "Implicit IAM Role created for O11y Event Emitter function"
    Value: !GetAtt O11yEventEmitterFunctionRole.Arn
